import os
import time
import json
import random
from datetime import datetime
from kafka import KafkaProducer

KAFKA_BOOTSTRAP_SERVERS = os.getenv(
    "KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
TOPIC = os.getenv("TOPIC", "app-logs")

producer = KafkaProducer(
    bootstrap_servers=KAFKA_BOOTSTRAP_SERVERS,
    value_serializer=lambda v: json.dumps(v).encode("utf-8"),
    linger_ms=10,
    acks=1,
)

SEVERITIES = ["INFO", "WARN", "ERROR"]
SERVICES = ["auth", "payments", "orders", "inventory", "search"]


def gen_message():
    severity = random.choices(SEVERITIES, weights=[0.7, 0.2, 0.1])[0]
    service = random.choice(SERVICES)
    msg = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "service": service,
        "severity": severity,
        "message": f"{severity} generated by {service}",
        "request_id": f"rid-{random.randint(1000, 9999)}",
        "details": {"user": random.randint(1, 200), "value": random.random()},
    }
    return msg


def main():
    print(f"Starting log generator -> {KAFKA_BOOTSTRAP_SERVERS} topic={TOPIC}")
    try:
        while True:
            msg = gen_message()
            producer.send(TOPIC, msg)
            # quick flush every now and then
            if random.random() < 0.05:
                producer.flush()
            # control rate: 10-40 messages/sec bursty
            time.sleep(random.uniform(0.02, 0.15))
    except KeyboardInterrupt:
        print("Stopping...")
    finally:
        producer.flush()
        producer.close()


if __name__ == "__main__":
    main()
